services:
  database:
    image: postgres:16.1-alpine
    ports:
      - "10001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    